main: DiamondStrider1\DiamondMinigames\Plugin
api: 3.25.0
version: 0.0.1

name: DiamondMinigames
description: Make creative minigames for your server.
website: https://github.com/Swift-Strider/DiamondMinigames
author: DiamondStrider1

permissions:
  diamondminigames.manage:
    description: Gives the power to fully manage diamondminigames
    default: op
  diamondminigames.play:
    description: Permission needed to play minigames
    default: true
